language: cpp
os:
  - linux
compiler:
  - gcc

before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse"
  - sudo apt-get update

install:
  - sudo apt-get install --no-install-recommends libnetcdff5
  - sudo apt-get install --no-install-recommends gfortran libnetcdf-dev python-numpy python-cffi

script:
  - tar xvzf kid_a_setup.tar.gz
  - cd kid_a_setup
  - patch -p1 < ../kid_a_setup.diff
  - make SHELL=/bin/bash CASE=1D COMPILER=gfortran NCPATH=/usr all
  #- bin/KiD_1D.exe
  - LD_LIBRARY_PATH=bin python ../kid.py
